### PR TITLE
added upm support

### PR DESCRIPTION
**Pull request by lvgrecords**

### CODE REVIEW

**Comment by lvgrecords** [comment]
@yankooliveira please take a look adding upm support

I'll replace `funzygames` identifier in case we are going to proceed with it at all
10x

**Comment by yankooliveira** [comment]
Hi Vitalii,
I have to double check a few things related to my current contract & code ownership before uploading new code to this repo, will try to look at this in the coming weeks

**Comment by jasursadikov** [comment]
@yankooliveira any updates?

**Comment by lvgrecords** [comment]
closing due no activity for some time

in case going back working on it - just restore branch/reopen PR

**Pull request closed without merging**
